# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1450, 830)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layout_table_other = QtWidgets.QVBoxLayout()
        self.layout_table_other.setObjectName("layout_table_other")
        self.PdTable = QtWidgets.QTableWidget(self.centralwidget)
        self.PdTable.setObjectName("PdTable")
        self.PdTable.setColumnCount(0)
        self.PdTable.setRowCount(0)
        self.layout_table_other.addWidget(self.PdTable)
        self.layout_buttons_and_spinbox = QtWidgets.QHBoxLayout()
        self.layout_buttons_and_spinbox.setObjectName("layout_buttons_and_spinbox")
        self.lay_descr = QtWidgets.QVBoxLayout()
        self.lay_descr.setObjectName("lay_descr")
        self.layout_spin_lab = QtWidgets.QHBoxLayout()
        self.layout_spin_lab.setObjectName("layout_spin_lab")
        self.label_partition = QtWidgets.QLabel(self.centralwidget)
        self.label_partition.setObjectName("label_partition")
        self.layout_spin_lab.addWidget(self.label_partition)
        self.spinBox_partition = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_partition.setObjectName("spinBox_partition")
        self.layout_spin_lab.addWidget(self.spinBox_partition)
        self.lay_descr.addLayout(self.layout_spin_lab)
        self.but_descr = QtWidgets.QPushButton(self.centralwidget)
        self.but_descr.setObjectName("but_descr")
        self.lay_descr.addWidget(self.but_descr)
        self.layout_buttons_and_spinbox.addLayout(self.lay_descr)
        self.layout_button_task = QtWidgets.QVBoxLayout()
        self.layout_button_task.setObjectName("layout_button_task")
        self.button_test_task = QtWidgets.QPushButton(self.centralwidget)
        self.button_test_task.setObjectName("button_test_task")
        self.layout_button_task.addWidget(self.button_test_task)
        self.button_main_task = QtWidgets.QPushButton(self.centralwidget)
        self.button_main_task.setObjectName("button_main_task")
        self.layout_button_task.addWidget(self.button_main_task)
        self.layout_buttons_and_spinbox.addLayout(self.layout_button_task)
        self.layout_table_other.addLayout(self.layout_buttons_and_spinbox)
        self.horizontalLayout_3.addLayout(self.layout_table_other)
        self.label_graph_labels = QtWidgets.QVBoxLayout()
        self.label_graph_labels.setObjectName("label_graph_labels")
        self.layout_three_labels = QtWidgets.QVBoxLayout()
        self.layout_three_labels.setObjectName("layout_three_labels")
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setObjectName("MplWidget")
        self.layout_three_labels.addWidget(self.MplWidget)
        self.label_dif = QtWidgets.QLabel(self.centralwidget)
        self.label_dif.setObjectName("label_dif")
        self.layout_three_labels.addWidget(self.label_dif)
        self.label_eps = QtWidgets.QLabel(self.centralwidget)
        self.label_eps.setObjectName("label_eps")
        self.layout_three_labels.addWidget(self.label_eps)
        self.label_n_partition = QtWidgets.QLabel(self.centralwidget)
        self.label_n_partition.setObjectName("label_n_partition")
        self.layout_three_labels.addWidget(self.label_n_partition)
        self.label_graph_labels.addLayout(self.layout_three_labels)
        self.horizontalLayout_3.addLayout(self.label_graph_labels)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_partition.setText(_translate("MainWindow", "3"))
        self.but_descr.setText(_translate("MainWindow", "PushButton"))
        self.button_test_task.setText(_translate("MainWindow", "0"))
        self.button_main_task.setText(_translate("MainWindow", "PushButton"))
        self.label_dif.setText(_translate("MainWindow", "5"))
        self.label_eps.setText(_translate("MainWindow", "4"))
        self.label_n_partition.setText(_translate("MainWindow", "6"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
