# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lay_left = QtWidgets.QVBoxLayout()
        self.lay_left.setObjectName("lay_left")
        self.PdTable = QtWidgets.QTableWidget(self.centralwidget)
        self.PdTable.setObjectName("PdTable")
        self.PdTable.setColumnCount(0)
        self.PdTable.setRowCount(0)
        self.lay_left.addWidget(self.PdTable)
        self.lay_left_descr = QtWidgets.QHBoxLayout()
        self.lay_left_descr.setObjectName("lay_left_descr")
        self.lay_labels_spins = QtWidgets.QVBoxLayout()
        self.lay_labels_spins.setObjectName("lay_labels_spins")
        self.lay_T = QtWidgets.QHBoxLayout()
        self.lay_T.setObjectName("lay_T")
        self.label_T = QtWidgets.QLabel(self.centralwidget)
        self.label_T.setObjectName("label_T")
        self.lay_T.addWidget(self.label_T)
        self.doubleSpinBox_T = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_T.setObjectName("doubleSpinBox_T")
        self.lay_T.addWidget(self.doubleSpinBox_T)
        self.lay_labels_spins.addLayout(self.lay_T)
        self.lay_n = QtWidgets.QHBoxLayout()
        self.lay_n.setObjectName("lay_n")
        self.label_n = QtWidgets.QLabel(self.centralwidget)
        self.label_n.setObjectName("label_n")
        self.lay_n.addWidget(self.label_n)
        self.spinBox_n = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_n.setObjectName("spinBox_n")
        self.lay_n.addWidget(self.spinBox_n)
        self.lay_labels_spins.addLayout(self.lay_n)
        self.lay_m = QtWidgets.QHBoxLayout()
        self.lay_m.setObjectName("lay_m")
        self.label_m = QtWidgets.QLabel(self.centralwidget)
        self.label_m.setObjectName("label_m")
        self.lay_m.addWidget(self.label_m)
        self.spinBox_m = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_m.setObjectName("spinBox_m")
        self.lay_m.addWidget(self.spinBox_m)
        self.lay_labels_spins.addLayout(self.lay_m)
        self.lay_left_descr.addLayout(self.lay_labels_spins)
        self.lay_left.addLayout(self.lay_left_descr)
        self.horizontalLayout_2.addLayout(self.lay_left)
        self.lay_right = QtWidgets.QVBoxLayout()
        self.lay_right.setObjectName("lay_right")
        self.MplGraph = MyGraph(self.centralwidget)
        self.MplGraph.setObjectName("MplGraph")
        self.lay_right.addWidget(self.MplGraph)
        self.lay_buttons = QtWidgets.QHBoxLayout()
        self.lay_buttons.setObjectName("lay_buttons")
        self.checkBox_lays = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_lays.setObjectName("checkBox_lays")
        self.lay_buttons.addWidget(self.checkBox_lays)
        self.pushButton_task = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_task.setObjectName("pushButton_task")
        self.lay_buttons.addWidget(self.pushButton_task)
        self.pushButton_descr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_descr.setObjectName("pushButton_descr")
        self.lay_buttons.addWidget(self.pushButton_descr)
        self.lay_right.addLayout(self.lay_buttons)
        self.horizontalLayout_2.addLayout(self.lay_right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_T.setText(_translate("MainWindow", "3"))
        self.label_n.setText(_translate("MainWindow", "1"))
        self.label_m.setText(_translate("MainWindow", "2"))
        self.checkBox_lays.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_task.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_descr.setText(_translate("MainWindow", "PushButton"))
from MyGraph import MyGraph


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
